version: 0.0
os: linux
files:
  - source: /app
    destination: /data/web-project/application
  - source: /scripts/kklib.service
    destination: /etc/systemd/system
permissions:
  - object: /data/web-project/application
    pattern: "**"
    owner: www-data
    group: www-data
    type:
      - file
  - object: /data/web-project/application
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
hooks:
  ApplicationStop:
    - location: scripts/blocktraffic.sh
      timeout: 300
      runas: root
    - location: scripts/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/blocktraffic.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/allowtraffic.sh
      timeout: 300
      runas: root
